pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'miguel1203/gestion-categories'
        IMAGE_TAG = 'dev'
        DOCKER_USER = 'miguel1203'
        DOCKER_PASS = 'dckr_pat_5CQzKCl99YfG_0nuHQMiuxUw6AY'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }

        stage('Build Application') {
            steps {
                echo 'Building Spring Boot Expense Service...'
                dir('Back/ms_categories') {
                    sh 'chmod +x ./mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Copy JAR to Dockerfile location') {
            steps {
                echo 'Copying JAR to Dockerfile location...'
                sh '''
                    mkdir -p ./Back/ms_categories/target
                    cp ./Back/ms_expense/ms_categories/target/*.jar ./Back/ms_categories/target/ || echo "JAR already in correct location"
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                echo 'Building and pushing Docker image for Expense Service...'
                dir('Back/ms_expense') {
                    script {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'

                        def image = docker.build("${DOCKER_HUB_REPO}:${IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Deploy Application') {
            steps {
                echo 'Deploying Expense Service DEV...'
                sh '''
                    echo "🚀 Desplegando Expense Service DEV..."
                    docker stop ms_expense-dev || true
                    docker rm ms_expense-dev || true

                    docker run -d \
                      --name ms_expense-dev \
                      --network gestion-gastos-dev_default \
                      -p 8112:8110 \
                      -e SPRING_PROFILES_ACTIVE=dev \
                      -e SPRING_DATASOURCE_URL="jdbc:postgresql://DataBase-dev:5432/gestion_gastos_dev" \
                      -e SPRING_DATASOURCE_USERNAME=postgres \
                      -e SPRING_DATASOURCE_PASSWORD=dev123456 \
                      ${DOCKER_HUB_REPO}:${IMAGE_TAG}
                '''
            }
        }


    }

}
