pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'miguel1203/gestion-expense'
        IMAGE_TAG = 'dev'
        DOCKER_USER = 'miguel1203'
        DOCKER_PASS = 'dckr_pat_5CQzKCl99YfG_0nuHQMiuxUw6AY'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }

        stage('Deploy Database') {
            steps {
                echo 'Deploying PostgreSQL DEV...'
                dir('DB') {
                    sh '''
                        echo "🚀 Desplegando PostgreSQL DEV..."
                        docker compose -f docker-compose-dev.yml -p gestion-gastos-dev up -d
                        sleep 10
                    '''
                }
            }
        }

        stage('Build Application') {
            steps {
                echo 'Building Spring Boot Expense Service...'
                dir('Back/ms_expense/ms_expense') {
                    sh 'chmod +x ./mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Copy JAR to Dockerfile location') {
            steps {
                echo 'Copying JAR to Dockerfile location...'
                sh '''
                    mkdir -p ./Back/ms_expense/target
                    cp ./Back/ms_expense/ms_expense/target/*.jar ./Back/ms_expense/target/
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                echo 'Building and pushing Docker image for Expense Service...'
                dir('Back/ms_expense') {
                    script {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'

                        def image = docker.build("${DOCKER_HUB_REPO}:${IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Deploy Application') {
            steps {
                echo 'Deploying Expense Service DEV...'
                sh '''
                    echo "🚀 Desplegando Expense Service DEV..."
                    docker network create gestios-gastos-back-dev || true
                    docker network connect gestios-gastos-back-dev DataBase-dev || true
                    
                    docker stop msexpense-dev || true
                    docker rm msexpense-dev || true

                    docker run -d \
                      --name msexpense-dev \
                      --network gestios-gastos-back-dev \
                      -p 8082:8080 \
                      -e SPRING_PROFILES_ACTIVE=dev \
                      -e SPRING_DATASOURCE_URL="jdbc:postgresql://DataBase-dev:5432/gestion_gastos_dev" \
                      -e SPRING_DATASOURCE_USERNAME=postgres \
                      -e SPRING_DATASOURCE_PASSWORD=dev123456 \
                      -e CATEGORIES_SERVICE_URL=http://mscategories-dev:8090 \
                      ${DOCKER_HUB_REPO}:${IMAGE_TAG}
                '''
            }
        }


    }

}
