pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'miguel1203/gestion-income'
        IMAGE_TAG = 'dev'
        DOCKER_USER = 'miguel1203'
        DOCKER_PASS = 'dckr_pat_5CQzKCl99YfG_0nuHQMiuxUw6AY'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }


        stage('Build Application') {
            steps {
                echo 'Building Spring Boot Income Service...'
                dir('Back/ms_income') {
                    sh 'chmod +x ./mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Copy JAR to Dockerfile location') {
            steps {
                echo 'Copying JAR to Dockerfile location...'
                sh '''
                    mkdir -p ./Back/ms_income/target
                    cp ./Back/ms_income/target/*.jar ./Back/ms_income/target/ || echo "JAR already in correct location"
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                echo 'Building and pushing Docker image for Income Service...'
                dir('Back/ms_income') {
                    script {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'

                        def image = docker.build("${DOCKER_HUB_REPO}:${IMAGE_TAG}")
                        image.push()
                    }
                }
            }
        }

        stage('Deploy Application') {
            steps {
                echo 'Deploying Income Service DEV...'
                sh '''
                    echo "🚀 Desplegando Income Service DEV..."
                    docker network create gestios-gastos-back-dev || true
                    
                    docker stop ms_income-dev || true
                    docker rm ms_income-dev || true

                    docker run -d \
                      --name ms_income-dev \
                      --network gestios-gastos-back-dev \
                      -p 8102:8100 \
                      -e SPRING_PROFILES_ACTIVE=dev \
                      -e SPRING_DATASOURCE_URL="jdbc:postgresql://DataBase-dev:5432/gestion_gastos_dev" \
                      -e SPRING_DATASOURCE_USERNAME=postgres \
                      -e SPRING_DATASOURCE_PASSWORD=dev123456 \
                      -e CATEGORIES_SERVICE_URL=http://ms_categories-dev:8090 \
                      ${DOCKER_HUB_REPO}:${IMAGE_TAG}
                '''
            }
        }


    }

}
