version: '3.8'

services:
  postgres-qa:
    image: postgres:15
    container_name: DataBase-qa
    environment:
      POSTGRES_DB: gestion_gastos_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qa123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_qa_data:/var/lib/postgresql/data
      - ./init-qa.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_qa_data: