version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-expense
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: postgres -c listen_addresses='*' -c log_connections=on

volumes:
  postgres_data:
