name: Build ms_expense

on:
  pull_request:
    branches: ["main", "dev", "qa"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant execute permission for mvnw
        working-directory: Back/ms_expense/ms_expense
        run: chmod +x mvnw

      - name: Build with Maven (skip tests)
        working-directory: Back/ms_expense/ms_expense
        run: ./mvnw clean package -DskipTests
