name: Deploy QA

on:
  workflow_dispatch:
  push:
    branches: ["qa"]
  pull_request:
    branches: ["qa"]

jobs:
  deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Deploy Database
      - name: Deploy PostgreSQL QA
        working-directory: ./DB
        run: |
          echo "🚀 Desplegando PostgreSQL QA..."
          docker compose -f docker-compose-qa.yml -p expense-db-qa up -d
          sleep 30

      # Build Application
      - name: Build with Maven
        working-directory: ./Back/ms_expense/ms_expense
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Copy JAR to Dockerfile location
        run: |
          mkdir -p ./Back/ms_expense/target
          cp ./Back/ms_expense/ms_expense/target/*.jar ./Back/ms_expense/target/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image QA
        working-directory: ./Back/ms_expense
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gestion-back:qa .
          docker push ${{ secrets.DOCKER_USERNAME }}/gestion-back:qa

      # Deploy Application
      - name: Deploy Application QA
        run: |
          echo "🚀 Desplegando aplicación QA..."
          docker stop gestion-back-qa || true
          docker rm gestion-back-qa || true

          docker run -d \
            --name gestion-back-qa \
            --network expense-db-qa_default \
            -p 8081:8080 \
            -e SPRING_PROFILES_ACTIVE=qa \
            -e SPRING_DATASOURCE_URL="jdbc:postgresql://postgres-expense-qa:5432/expense_db_qa" \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=qa123456 \
            ${{ secrets.DOCKER_USERNAME }}/gestion-back:qa

      - name: Health Check QA
        run: |
          echo "🔍 Verificando salud de la aplicación QA..."
          sleep 45
          curl -f http://localhost:8081/actuator/health || exit 1
          echo "✅ Aplicación QA desplegada exitosamente!"
