name: Release DB Dev

on:
  workflow_dispatch: # Solo se ejecuta manualmente

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start DB with Docker Compose (Dev)
        working-directory: ./DB
        run: |
          docker compose -p expense-db-dev up -d
